Repository imhardikdesai/DSA-Algorithms, pull requests merged in 2022-10, with the labels that each got.

#1 Create Merge_sort.c
  Merge_sort.c
Labels: hactoberfest

#2 Count Sort
  Count_Sort.py
Labels: hactoberfest

#3 Added Bubble sort algorithm by using Python
  Python Programs/Bubble_Sort.py
Labels: hactoberfest

#4 add binary search problem
  Cpp_Program/Search_Insertion_Pos.cpp
Labels: hactoberfest

#6 Linear Search in python and c
  C Programs/Linear_search.c
  Python Programs/Linear_search.py
Labels: hactoberfest

#7 Cloning a linked list using pointers
  C++ Programs/cloning_LinkedList.cpp
Labels: hactoberfest

#8 Create dijkstra_algorithm.cpp
  C++ Programs/dijkstra_algorithm.cpp
Labels: hactoberfest

#9 Create Minimum Elements to Add to Form a Given Sum.py
  Python Programs/Minimum Elements to Add to Form a Given Sum.py
Labels: hactoberfest

#11 prism's algo in cpp
  C++ Programs/prism_algo.cpp
Labels: hactoberfest

#14 Factorial Of Large Numbers
  Python Programs/Factorial_Of_Large_Numbers.py
Labels: hactoberfest

#15 Create PrimeFactors.cpp
  C++ Programs/PrimeFactors.cpp
Labels: hactoberfest

#17 Added bubble sort for C++
  C++ Programs/bubble_sort.cpp
Labels: hactoberfest

#18 Added
  C++ Programs/Minimum Spanning Tree.cpp
  C++ Programs/Primes and PrimeFactors.cpp
Labels: hactoberfest

#19 added gradient descent
  Python Programs/gradient_descent.py
Labels: hactoberfest

#20 Kruskal Algorithm
  C++ Programs/KruskalAlgo.cbp
Labels: hactoberfest

#21 Added code for flattening a linked list
  C++ Programs/Flattening_a_Linked_List.cpp
Labels: hactoberfest

#23 Create Selection Sort
  Java Programs/Selection_Sort.java
Labels: hactoberfest, hactoberfest- accepted

#25 Create Factorial.cpp
  C++ Programs/Factorial.cpp
Labels: hactoberfest, hactoberfest- accepted

#24 Create insertionsort.cpp
  C++ Programs/insertionsort.cpp
  C++ Programs/merge_sort.cpp
Labels: hactoberfest, hactoberfest- accepted

#26 added definite integrals calculator
  Python Programs/def_integrals.py
Labels: hactoberfest, hactoberfest- accepted

#29 feat : JS Palindrome
  JavaScript Programs/Palindrome_Checker.js
Labels: hactoberfest, hactoberfest- accepted

#27 C# codes
  HeapSort.cs
  Insertionsort.cs
  LinkedListImplementation.cs
  RadixSort.cs
  StackTrace.cs
Labels: hactoberfest, hactoberfest- accepted

#30 Moore's Voting Algorithm
  C++ Programs/Moore's Voting Algorithms.cpp
Labels: hactoberfest, hactoberfest- accepted

#31 Added 3 python programs
  Python Programs/collatz_sequence.py
  Python Programs/kaprekar_const.py
  Python Programs/longest_common_prefix.py
Labels: hactoberfest, hactoberfest- accepted

#32 CPP code of K Closest Points to Origin (using heap)
  C++ Programs/K Closest Points to Origin.cpp
Labels: hactoberfest, hactoberfest- accepted

#34 Create countingsort.cpp
  C++ Programs/countingsort.cpp
Labels: hactoberfest, hactoberfest- accepted

#35 HeapSort.cpp
  C++ Programs/HeapSort.cpp
Labels: hactoberfest, hactoberfest- accepted

#36 RadixSort.cpp
  C++ Programs/RadixSort.cpp
Labels: hactoberfest, hactoberfest- accepted

#37 ShellSort.cpp
  C++ Programs/ShellSort.cpp
Labels: hactoberfest, hactoberfest- accepted

#38 added binary_search.cpp
  C++ Programs/binary_search.cpp
Labels: hactoberfest, hactoberfest- accepted

#39 hacktoberfest-2022
  C++ Programs/Boyer Moore's Voting Algorithms.cpp
Labels: hactoberfest, hactoberfest- accepted

#40 Create selection-sort.cpp
  C++ Programs/selection-sort.cpp
Labels: hactoberfest, hactoberfest- accepted

#45 Kadane's Algorithms
  C++ Programs/Kadane's Algorithms.cpp
Labels: hactoberfest, hactoberfest- accepted

#42 Floyd Warshall Algo
  C++ Programs/Floyd Warshall.cpp
Labels: hactoberfest, hactoberfest- accepted

#43 feat: JS Time Conversion
  JavaScript Programs/TimeConversion.js
Labels: hactoberfest, hactoberfest- accepted

#44 Create reverse_LinkedList_using_stack.cpp
  C++ Programs/reverse_LinkedList_using_stack.cpp
Labels: hactoberfest, hactoberfest- accepted

#48 Boundary traversal of binary tree
  C++ Programs/boundarytraversal_bt.cpp
Labels: hactoberfest, hactoberfest- accepted

#47 Added PriorityQueue
  C++ Programs/PriorityQueue.cpp
Labels: hactoberfest, hactoberfest- accepted

#55 Create Sieve of Eratosthenes.cpp
  C++ Programs/Sieve of Eratosthenes.cpp
Labels: hactoberfest, hactoberfest- accepted

#50 Create queue.cpp
  C++ Programs/queue.cpp
Labels: hactoberfest, hactoberfest- accepted

#51 Added Quick Sort
  C++ Programs/quickSort.cpp
Labels: hactoberfest, hactoberfest- accepted

#53 added dfs
  C++ Programs/Depth_First_Search_Graph.cpp
Labels: hactoberfest, hactoberfest- accepted

#52 Create sudokuSolver.cpp
  C++ Programs/sudokuSolver.cpp
Labels: hactoberfest, hactoberfest- accepted

#57 Add knapsack algorithm and test function
  Python Programs/Knapsack.py
Labels: hactoberfest, hactoberfest- accepted

#56 added C++ for Fibonacci Series
  C++ Programs/fibonacci_series.cpp
Labels: hactoberfest, hactoberfest- accepted

#54 Create N_QUEEN_ino(n).cpp
  C++ Programs/N_QUEEN_ino(n).cpp
Labels: hacktoberfest, hacktoberfest- accepted

#58 Added python program files related to DSA (Hacktoberfest)
  Python Programs/AVL Tree(Balanced Binary Search Tree).py
  Python Programs/Bellman Ford algorithm.py
  Python Programs/Binary Search Tree.py
  Python Programs/Breadth First Search.py
  Python Programs/Depth First Search.py
  Python Programs/Dijkstra's Shortest Path algorithm.py
  Python Programs/Heap_Python Buitlt in function.py
  Python Programs/Linked Lists.py
  Python Programs/Merge Sort.py
  Python Programs/Prims-Jarnik Algorithm MST.py
  Python Programs/Queue.py
  Python Programs/Quick sort.py
  Python Programs/Selection sort.py
  Python Programs/Stack.py
Labels: hacktoberfest, hacktoberfest- accepted

#60 my commit 1 for hactoberfest
  C++ Programs/LongestPalindrome.cpp
  C++ Programs/buySellStocks.cpp
Labels: hacktoberfest, hacktoberfest- accepted

#63 Added Job Sequencing Algorithm
  C++ Programs/JobSequencing.cpp
Labels: hacktoberfest, hacktoberfest- accepted

#64 Create code for finding the SQUARE ROOT of any no.cpp
  C++ Programs/code for finding the SQUARE ROOT  of any no.cpp
Labels: hacktoberfest, hacktoberfest- accepted

#59 Randomized Select
  C++ Programs/Random_quickSort.cpp
  C++ Programs/bucket_sort.cpp
  C++ Programs/random_select.cpp
Labels: hacktoberfest, hacktoberfest- accepted

#65 Create Checking if binary tree is BST or not
  C++ Programs/Checking if binary tree is BST or not
Labels: hacktoberfest, hacktoberfest- accepted

#66 Dijkstra’s Algorithm Shortest distance Java
  Java Programs/DijkstrasAlgorithm.java
Labels: hacktoberfest, hacktoberfest- accepted

#67 Added Fractional Knapsack Problem
  C++ Programs/FractionalKnapsack.cpp
Labels: hacktoberfest, hacktoberfest- accepted

#68 Added Coin Change Problem
  C++ Programs/CoinChange.cpp
Labels: hacktoberfest, hacktoberfest- accepted

#69 Added Friends Pairing Problem
  C++ Programs/FriendsPairing.cpp
Labels: hacktoberfest, hacktoberfest- accepted

#70 Added 0-1 Knapsack Problem
  C++ Programs/0-1Knapsack.cpp
Labels: hacktoberfest, hacktoberfest- accepted

#71 Added Subset Sum Problem
  C++ Programs/SubsetSum.cpp
Labels: hacktoberfest, hacktoberfest- accepted

#72 circulat linked list
  C Programs/LinkedList.c
Labels: hacktoberfest, hacktoberfest- accepted

#73 Sliding Window Maximum
  C++ Programs/SlidingWindowMaximum.cpp
Labels: hacktoberfest, hacktoberfest- accepted

#74 Added a diff utility written in Python
  Python Programs/diff.py
Labels: hacktoberfest, hacktoberfest- accepted

#75 added swap number
  C Programs/swap_number.c
Labels: hacktoberfest, hacktoberfest- accepted

#76 Create trie.cpp
  trie.cpp
Labels: hacktoberfest, hacktoberfest- accepted

#78 Create count_sort.c
  C Programs/count_sort.c
Labels: hacktoberfest, hacktoberfest- accepted

#81 Created Topological-Sort Algorithm in C++
  C++ Programs/Topological-Sorting.cpp
Labels: hacktoberfest- accepted

#83 Created merge sort.cs
  C# Programs/merge sort.cs
Labels: hacktoberfest, hacktoberfest- accepted

#84 Stock Span Problem
  C++ Programs/Stock Span.cpp
Labels: hacktoberfest, hacktoberfest- accepted

#86 Merge Two Sorted Linked Lists.cpp
  C++ Programs/Merge Two Sorted Linked Lists.cpp
Labels: hacktoberfest, hacktoberfest- accepted

#87 estinationCity.cpp
  C++ Programs/DestinationCity.cpp
Labels: hacktoberfest, hacktoberfest- accepted

#88 Created Binary Search.c
  C Programs/Binary Search.c
Labels: hacktoberfest, hacktoberfest- accepted

#89 Create cycleSort.cpp
  C++ Programs/cycleSort.cpp
Labels: hacktoberfest, hacktoberfest- accepted

#91 Create Count of Subsets with given Difference.cpp
  C++ Programs/Count of Subsets with given Difference.cpp
Labels: hacktoberfest, hacktoberfest- accepted

#92 linkedlist
  C++ Programs/reverseLinkedList.cpp
Labels: hacktoberfest, hacktoberfest- accepted

#94 Trapping-rain-water problem cpp
  C++ Programs/Trapping-rain-water.cpp
Labels: hacktoberfest, hacktoberfest- accepted

#97 stack operation
  C Programs/Operation.c
Labels: hacktoberfest, hacktoberfest- accepted

#98 Create LongestPalindromicSubstring.py
  Python Programs/LongestPalindromicSubstring.py
Labels: hacktoberfest- accepted

#99 Create Trapping_Rain_Water.py
  Python Programs/Trapping_Rain_Water.py
Labels: hacktoberfest- accepted

#102 Add Binary tree maximum path sum, Add gitignore file
  .gitignore
  C++ Programs/Binary_tree_maximum_path_sum.cpp
Labels: hacktoberfest- accepted

#103 selection sort in c
  C Programs/Selection_Sort.c
Labels: hacktoberfest- accepted

#105 longestValidParentheses.py
  Python Programs/longestValidParentheses.py
Labels: hacktoberfest- accepted

#111 Create Insertion_sort.c
  C Programs/Insertion_sort.c
Labels: hacktoberfest- accepted
